### ISSUE TITLE
Customize background color based on value being selected

### ISSUE THREAD

**Issue by rezastallone** [code-mc/linear-time-picker#2]
Is it possible to customize background color based on value being selected or scrolled ? i would like to create gradient background that change when user scroll from top to bottom or the opposite

**Comment by code-mc** [comment]
Check out https://github.com/code-mc/linear-time-picker/blob/master/app/src/main/java/net/steamcrafted/lineartimepickerexample/ColorAdapter.java this is a more advanced "color selector" that morphs colored rectangles. You could modify this to change the background to the currently selected color by drawing one big rectangle instead of all the small ones. I think cloning the repo and playing around with the sample app will help you understand the rather complex adapter API.

If you have any more questions feel free to ask.
